INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (5, 'Chương 1:Giới Thiệu', 2850);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (6, 'Chương 2:Ôn tập ES6', 2850);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (7, 'Chương 3:React,ReactDOM', 2850);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (8, 'Chương 1:Cơ bản về NodeJS', 2851);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (9, 'Chương 2: Xử lý bất đồng bộ trong NodeJS', 2851);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (11, 'Chương 3:NodeJS và các cơ sở dữ liệu', 2851);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (13, 'Chương 1:Cơ bản về Python', 2853);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (14, 'Chương 2:Cấu trúc điều khiển và hàm trong Python', 2853);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (16, 'Chương 3:Các ứng dụng của Python', 2853);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (17, 'Chương 1: Giới thiệu về HTML', 2855);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (18, 'Chương 2: Giới thiệu về CSS', 2855);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (19, 'Chương 3: Tiên tiến hơn về HTML và CSS', 2855);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (20, 'Chương 1: Giới thiệu về JavaScript', 2858);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (21, 'Chương 2: Xử lý sự kiện và DOM', 2858);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (23, 'Chương 3: Tiên tiến hơn về JavaScript', 2858);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (24, 'Chương 1: Giới thiệu về Java', 2856);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (25, 'Chương 2: Lập trình hướng đối tượng trong Java', 2856);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (26, 'Chương 3: Tiên tiến hơn về Java', 2856);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (27, 'Chương 1: Giới thiệu về Bootstrap', 2860);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (28, 'Chương 2: Thiết kế trang web với Bootstrap', 2860);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (29, 'Chương 3: Tùy chỉnh giao diện với Bootstrap', 2860);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (30, 'Chương 1: Giới thiệu về Laravel', 2862);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (31, '
Chương 2: Thiết kế cơ sở dữ liệu và quản lý migrations', 2862);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (32, 'Chương 3: Xây dựng tính năng và giao diện cho website', 2862);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (33, 'admin', null);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (34, 'emtienday2265', null);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (35, 'minhjrt@gmail.COM', null);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (36, 'tienuser@haui.edu.vn', null);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (37, 'trine', null);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (38, 'viettein200222@haui.edu.vn', null);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (39, 'viettien02@gmail.com', null);
INSERT INTO khoahoc.chapter (tps_id, tps_title, tps_idcourse) VALUES (40, 'viettien02@haui.edu.vn', null);
